# Pure Python vs. Numpy - Lab

## Introduction 

Numpy, Scipy and Pandas libraries provide a significant increase in computational efficiency with complex mathematical operations as compared to Python's built in arithmetic functions.  In this lab we shall calculate and compare the processing speed required for calculating a dot product both using basic arithmatic operations in Python and Numpy's `.dot()` method. 

## Objectives
You will be able to:
* Compare the performance of high dimensional matrix operations in Numpy vs. pure Python

## Problem
> **Write a routine to calculate the dot product between two 200 x 200 dimensional matrices using:**

> **a) Pure Python**

> **b) Numpy's `.dot()`**


### Create two 200 x 200 matrices in Python and fill them with random values using `np.random.rand()` 

In [2]:
# Compare 200x200 matrix-matrix multiplication speed
import numpy as np

SIZE = 200
# Set up the variables
A = np.random.rand(SIZE,SIZE)
B = np.random.rand(SIZE,SIZE)

print(A)
print(B)

[[0.24095531 0.35026392 0.48195847 ... 0.14886509 0.82823602 0.62236627]
 [0.91928522 0.88500084 0.99669685 ... 0.27701252 0.51047754 0.8843856 ]
 [0.06417626 0.81249655 0.26530374 ... 0.80154405 0.44899479 0.25947668]
 ...
 [0.64978666 0.92161424 0.11301921 ... 0.78713106 0.88397722 0.89576411]
 [0.22669999 0.92743573 0.97339864 ... 0.55336528 0.98642698 0.86293464]
 [0.41673222 0.06680481 0.11384026 ... 0.69991529 0.83851993 0.42710511]]
[[0.37202223 0.77990785 0.66009758 ... 0.09361305 0.21820422 0.53687922]
 [0.69250322 0.69445329 0.45064159 ... 0.27306321 0.98172885 0.45854037]
 [0.81449027 0.30239823 0.77301183 ... 0.84885229 0.17513785 0.18962478]
 ...
 [0.07686198 0.05974704 0.21160549 ... 0.44340491 0.46354518 0.96791073]
 [0.08871654 0.52441275 0.33656984 ... 0.95493916 0.27334738 0.56687541]
 [0.29709334 0.39681201 0.52173863 ... 0.259003   0.85291415 0.2386383 ]]


### Pure Python

* Initialize an zeros filled numpy matrix with necessary rows and columns for storing result. 
* In Python Calculate the dot product using the formula 
![](formula.png)
* Use Python's `timeit` library to calculate the processing time. 
* [Visit this link](https://www.pythoncentral.io/time-a-python-function/) for an indepth explanation on how to time a function or routine in python. 

**Hint**: Use nested for loop for accessing, calculating and storing each scalar value in the result matrix.

In [3]:
import timeit

# Start the timer
start = timeit.default_timer()

# Matrix multiplication in pure Python
out2 = np.zeros((SIZE,SIZE))

for i in range(SIZE):
  for j in range(SIZE):
    for k in range(SIZE):
      
        out2[i,k] += A[i,j]*B[j,k]


time_spent = timeit.default_timer() - start

print('Pure Python Time:', time_spent, 'sec.')

Pure Python Time: 6.545228893000967 sec.


## Numpy 
Set the timer and calculate the time taken by `.dot()` function for multiplying A and B 


In [4]:
# start the timer
start = timeit.default_timer()

# Matrix multiplication in numpy
out = A.dot(B)

time_spent = timeit.default_timer() - start
print('Numpy Time:', time_spent, 'sec.')

Numpy Time: 0.023485424000682542 sec.


### Your comments 

NumPy is much faster and more efficient than pure Python.

## Summary

In this lab, we performed a quick comparison between calculating a dot product in numpy vs python built in function. We saw that Numpy is computationally much more efficient that Python code due to highly sophisticated implementation of Numpy source code. You are encouraged to always perform such tests to fully appreciate the use of an additional library in Python. 